### ISSUE TITLE
Get the drift wave code working

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO-Tokamak#1]
Eventually we will want:
 - 2D cylindrical
 - 3D extruded / rotated grids
 - Oblique boundary conditions
 - realistic magnetic field

**Comment by jwscook** [comment]
BCs are sorted out.
Magnetic field points data is normalised  - what is the scaling factor @futtersack ?

**Comment by oparry-ukaea** [comment]
Non-normalised B fields received from @futtersack .

**Comment by jwscook** [comment]
done
